web_app/admin/profile/forms.py
from flask_wtf import FlaskForm
from flask_wtf.recaptcha import validators, RecaptchaField
from wtforms import StringField
from wtforms.fields.choices import RadioField
from wtforms.fields.simple import FileField, PasswordField, BooleanField, TelField
from wtforms.validators import DataRequired, Email, EqualTo, Length
from flask_wtf.file import FileRequired


class LoginForm(FlaskForm):
    username = StringField('Логин', validators=[DataRequired("Данные не введены")])
    password = PasswordField('Пароль', validators=[DataRequired("you didn't input anithing")])
    remember = BooleanField('Запомнить меня')


# class SearshForm(FlaskForm):
#     searchbar = StringField()


class VerificationForm(FlaskForm):
    choose = RadioField('Выберите действие', choices=[(True,'Подтвердить валидацию'),(False,'Отклонить')])

web_app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__, template_folder='templates', url_prefix='/admin', static_folder='static')

from .profile import views

web_app/admin/profile/views.py
from flask_login.utils import login_required, logout_user
# from flask_mail import Message
from .. import admin
from flask import render_template, redirect, url_for, request, flash, send_from_directory
from ...database import db
from ...database.models import Admin, Client, Supervision, User
from .forms import LoginForm, VerificationForm
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, current_user
import smtplib
import email.message




def sum_all():
    users = User.query.order_by(User.id)
    dic = []
    
    for user in users:
        ar = {}
        if user.role:
            supervision = Supervision.query.filter_by(f_id=user.id).first()
            
        else:
            client = Client.query.filter_by(f_id=user.id).first()
            ar.setdefault('username', client.username)
            ar.setdefault('last_name', client.last_name)
            ar.setdefault('first_name', client.first_name)
            ar.setdefault('fat', client.fat)
            ar.setdefault('checked', client.checked)


        ar.setdefault('id', user.id)
        ar.setdefault('email', user.email)
        ar.setdefault('phone', user.phone)
        ar.setdefault('uniqe_hash', user.uniqe_hash)
        ar.setdefault('role', user.role)
        dic.append(ar)

    return dic



@admin.route('/', methods=['POST', 'GET'])
@login_required
def index():
    admin = Admin.query.filter_by(username = current_user.email).first()
    if not admin:
        return redirect(url_for('main.index'))
    # form = LoginForm()
    # if form.validate_on_submit():
    return redirect(url_for('admin.page'))
    #     admin = Admin.query.filter_by(username = form.username.data).first()
    #     if admin and admin.password == form.password.data:
    #         login_user(admin, form.remember.data)
    #         return redirect(url_for('admin.page'))
    #     else:
    #         flash('Admin not found')
    # return render_template('admin.html', form = form)

@admin.route('/page', methods=['POST', 'GET'])
@login_required
def page():
    admin = Admin.query.filter_by(username = current_user.email).first()
    if not admin:
        return redirect(url_for('main.index'))
    users = User.query.order_by(User.reg_data)
    count_client = Client.query.count()
    count_supervisor = Supervision.query.count()
    for client in users:
        print(client.id)
        print(type(client.id))
    print()
    return render_template('admin_page.html', clients = sum_all(), cc=count_client, cs=count_supervisor)



@admin.route('/<hash>')
def personality(hash):
    user = User.query.filter_by(uniqe_hash=hash).first()
    if user.role:
        client = Supervision.query.filter_by(f_id=user.id).first()
    else:
        client = Client.query.filter_by(f_id=user.id).first()
    files = []
    filenames =  client.filename
    print(type(filenames))
    for file in client.filename.split():
        files.append(file)
    return render_template('personality.html', client = user, about = client, files = files)

@admin.route('/<hash>/<file>')
@login_required
def dwn(hash, file):
    print(hash)
    print(file)
    user = User.query.filter_by(uniqe_hash=hash).first()
    print(user)
    if user.role:
        client = Supervision.query.filter_by(f_id=user.id).first()
    else:
        client = Client.query.filter_by(f_id=user.id).first()
    
    
    path = client.path_file
    
    
    return send_from_directory(path, file)

@admin.route('/confirm/<hash>', methods=['POST', 'GET'])
def confirm(hash):
    user = User.query.filter_by(uniqe_hash=hash).first()
    if user.role:
        client = Supervision.query.filter_by(f_id=user.id).first()
    else:
        client = Client.query.filter_by(f_id=user.id).first()
    
    client.checked = True

    # email_content = '''
    # <html>
    # <head>
    #     <title>verification video.pandabear.ru</title>
    # </head>
    # <body>
    #     Your document was checked. That's alright, you can login web-site now
    # </body> 
    # </html>
    # '''

    # msg = email.message.Message()
    # msg['Subject'] = "Verification"

    # msg['From'] = 'admin@pandabear.ru'
    # msg['To'] = 'popov2895@gmail.com'

    # password = 'AdminISP'
    # msg.add_header('Content-Type', 'text/html')
    # msg.set_payload(email_content)

    # s = smtplib.SMTP('mail.hosting.reg.ru:465')
    # s.starttls()

    # s.login(msg['From'], password)
    
    # s.sendmail(msg['From'], [msg['To']], msg.as_string())
    # s.quit()

    db.session.commit()
    return redirect(url_for('admin.page'))

@admin.route('/deconfirm/<hash>', methods=['POST', 'GET'])
def deconfirm(hash):
    user = User.query.filter_by(uniqe_hash=hash).first()
    if user.role:
        client = Supervision.query.filter_by(f_id=user.id).first()
    else:
        client = Client.query.filter_by(f_id=user.id).first()

    client.checked = False
    db.session.commit()
    return redirect(url_for('admin.page'))

web_app/admin/templates/admin.html
{% extends 'base.html' %}

{% block main %}
    <form action="" method="POST" class="form">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class='flash_error'>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        {% endwith %}
        {{ form.hidden_tag() }}
        <!-- <input type="text" class='form__el' name="username" id="" placeholder="Create your unique username">
        <input type="email" class='form__el' name="email" id="" placeholder="Write down your email">
        <input type="password" class='form__el' name="password" id="" placeholder="Create password">
        <input type="password" class='form__el' name="password_a" id="" placeholder="Repeat password">
        <input type="submit" class='form__el' value="Registration"> -->
        {% for line in form if line.name not in [ 'csrf_token', 'remember'] %}
            {{ line.label(class='form_label') }} 
            {% if line.errors %}
                {{ line(class='form_field_error' )}}
                {% for e in line.errors %}
                    {{ e }}
                {% endfor %}
            {% else %}
                {{ line( class= 'form_field') }}
            {% endif %}
        {% endfor %}
        <div class="remember">
            {{ form.remember( class= 'remember_field') }}{{ form.remember.label(class='form_label') }}
        </div>
        <input type="submit" class="form__submit" value="Подтвердить">
        
        
    </form>
{% endblock %}

web_app/admin/templates/admin_page.html
{% extends 'base.html' %}

{% block main %}
    <div class="admin__clients">
        Клиентов: {{cc}}
        Супервизоров: {{cs}}
        <div class="admin__titleline">
            <div class="clients_id">
                id
            </div>
            <div class="clients_email">
                Почта
            </div>
            <div class="clients_phone">
                Телефон
            </div>
            <div class="clients_fio">
                ФИО
            </div>
            <div class="clients_status">
                Статус
            </div>
            <div class="clients_role">
                Роль
            </div>
        </div>
        {%for user in clients%}
        <div class="clients_line">
            <div class="clients_id">
                <a class="clients_link" href="{{url_for('admin.personality', hash=user['uniqe_hash'])}}">{{user['id']}}</a>
            </div>
            <div class="clients_email">
                {{user['email']}}
            </div>
            <div class="clients_phone">
                {{user['phone']}}
            </div>
            <div class="clients_fio">
                {{user['last_name']}} {{user['first_name']}} {{user['fat']}}
            </div>
            <div class="clients_status">
                {%if user['checked']%}
                    <p class="clients_allow">Пройден</p> 
                {%else%}
                    <p class="clients_deny">Не пройден</p> 
                {%endif%}
                
            </div>
            <div class="clients_role">
                {%if user['role']%}
                <p class="clients__supervisor">Супервизор</p>
                {%else%}
                <p class="clients__client">Клиент</p>
                {%endif%}
                
            </div>
        </div>
        
        {%endfor%}
    </div>
{% endblock %}

web_app/admin/templates/personality.html
{% extends 'base.html' %}

{% block main %}
    <div class="admin__clients">
        
        <div class="p_line">
            
            <div class="p_username">
                <div class="p_title">Юзернейм пользователя</div>
                <div class="p_content">{{about['username']}}</div> 
            </div>
            <div class="p_fio">
                <div class="p_title">ФИО пользователя</div>
                <div class="p_content">{{about['last_name']}} {{about['first_name']}} {{about['fat']}}</div>
               
            </div>
            <div class="p_email">
                <div class="p_title">Email пользователя</div>
                <div class="p_content">{{client['email']}}</div>
                
            </div>
            <div class="p_phone">
                <div class="p_title">Телефон пользователя</div>
                <div class="p_content">{{client['phone']}}</div>
                
            </div>
            
            <div class="p_sertificate">
                <div class="p_title">Сертификаты:</div>
                {%for file in files%}
                <a target="_blank" href="{{url_for('admin.dwn',hash=client['uniqe_hash'], file=file)}}" class="p_sert">{{ file }}</a>
                {%endfor%}

                
            </div>
            <div class="p_form_confirm">
                {%if about['checked']%}
                <a class="reg_d p_btn" href="{{url_for('admin.deconfirm', hash=client['uniqe_hash'])}}">Отклонить</a>
                {%else%}
                <a class="reg_a p_btn" href="{{url_for('admin.confirm', hash=client['uniqe_hash'])}}">Подтвердить</a>
                {%endif%}
                
            </div>
        </div>
        
        
    </div>
{% endblock %}